# This file is generated by npmjs2nix. Do not edit.

{ src ? null, srcs ? null }:

{
  src = src;
  srcs = srcs;
  name = "npm-nix-sample-01";
  packageName = "npm-nix-sample-01";
  version = "0.1.0";
  bin = {
    sample-bcrypt-cli = "./bcrypt-cli.js";
  };
  dependencies = {
    abbrev = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      tarball = {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==";
      };
    };
    ansi-regex = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "3.0.0";
      tarball = {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-3.0.0.tgz";
        sha1 = "7QMXwyIGT3lGbAKWa922Bas32Zg=";
      };
    };
    aproba = {
      name = "aproba";
      packageName = "aproba";
      version = "1.2.0";
      tarball = {
        url = "https://registry.npmjs.org/aproba/-/aproba-1.2.0.tgz";
        sha512 = "Y9J6ZjXtoYh8RnXVCMOU/ttDmk1aBjunq9vO0ta5x85WDQiQfUF9sIPBITdbiiIVcBo03Hi3jMxigBtsddlXRw==";
      };
    };
    are-we-there-yet = {
      name = "are-we-there-yet";
      packageName = "are-we-there-yet";
      version = "1.1.5";
      tarball = {
        url = "https://registry.npmjs.org/are-we-there-yet/-/are-we-there-yet-1.1.5.tgz";
        sha512 = "5hYdAkZlcG8tOLujVDTgCT+uPX0VnpAH28gWsLfzpXYm7wP6mp5Q/gYyR7YQ0cKVJcXJnl3j2kpBan13PtQf6w==";
      };
    };
    balanced-match = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      tarball = {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "ibTRmasr7kneFk6gK4nORi1xt2c=";
      };
    };
    bcrypt = {
      name = "bcrypt";
      packageName = "bcrypt";
      version = "3.0.5";
      hasInstallationHooks = true;
      tarball = {
        url = "https://registry.npmjs.org/bcrypt/-/bcrypt-3.0.5.tgz";
        sha512 = "m4o91nB+Ce8696Ao4R3B/WtVWTc1Lszgd098/OIjU9D/URmdYwT3ooBs9uv1b97J5YhZweTq9lldPefTYZ0TwA==";
      };
      dependencies = {
        abbrev = {
          name = "abbrev";
          packageName = "abbrev";
          version = "1.1.1";
          tarball = {
            url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
            sha512 = "nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==";
          };
        };
        ansi-regex = {
          name = "ansi-regex";
          packageName = "ansi-regex";
          version = "2.1.1";
          tarball = {
            url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
            sha1 = "w7M6te42DYbg5ijwRorn7yfWVN8=";
          };
        };
        aproba = {
          name = "aproba";
          packageName = "aproba";
          version = "1.2.0";
          tarball = {
            url = "https://registry.npmjs.org/aproba/-/aproba-1.2.0.tgz";
            sha512 = "Y9J6ZjXtoYh8RnXVCMOU/ttDmk1aBjunq9vO0ta5x85WDQiQfUF9sIPBITdbiiIVcBo03Hi3jMxigBtsddlXRw==";
          };
        };
        are-we-there-yet = {
          name = "are-we-there-yet";
          packageName = "are-we-there-yet";
          version = "1.1.5";
          tarball = {
            url = "https://registry.npmjs.org/are-we-there-yet/-/are-we-there-yet-1.1.5.tgz";
            sha512 = "5hYdAkZlcG8tOLujVDTgCT+uPX0VnpAH28gWsLfzpXYm7wP6mp5Q/gYyR7YQ0cKVJcXJnl3j2kpBan13PtQf6w==";
          };
        };
        balanced-match = {
          name = "balanced-match";
          packageName = "balanced-match";
          version = "1.0.0";
          tarball = {
            url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
            sha1 = "ibTRmasr7kneFk6gK4nORi1xt2c=";
          };
        };
        brace-expansion = {
          name = "brace-expansion";
          packageName = "brace-expansion";
          version = "1.1.11";
          tarball = {
            url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
            sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
          };
        };
        chownr = {
          name = "chownr";
          packageName = "chownr";
          version = "1.1.1";
          tarball = {
            url = "https://registry.npmjs.org/chownr/-/chownr-1.1.1.tgz";
            sha512 = "j38EvO5+LHX84jlo6h4UzmOwi0UgW61WRyPtJz4qaadK5eY3BTS5TY/S1Stc3Uk2lIM6TPevAlULiEJwie860g==";
          };
        };
        code-point-at = {
          name = "code-point-at";
          packageName = "code-point-at";
          version = "1.1.0";
          tarball = {
            url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.1.0.tgz";
            sha1 = "DQcLTQQ6W+ozovGkDi7bPZpMz3c=";
          };
        };
        concat-map = {
          name = "concat-map";
          packageName = "concat-map";
          version = "0.0.1";
          tarball = {
            url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
            sha1 = "2Klr13/Wjfd5OnMDajug1UBdR3s=";
          };
        };
        console-control-strings = {
          name = "console-control-strings";
          packageName = "console-control-strings";
          version = "1.1.0";
          tarball = {
            url = "https://registry.npmjs.org/console-control-strings/-/console-control-strings-1.1.0.tgz";
            sha1 = "PXz0Rk22RG6mRL9LOVB/mFEAjo4=";
          };
        };
        core-util-is = {
          name = "core-util-is";
          packageName = "core-util-is";
          version = "1.0.2";
          tarball = {
            url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
            sha1 = "tf1UIgqivFq1eqtxQMlAdUUDwac=";
          };
        };
        debug = {
          name = "debug";
          packageName = "debug";
          version = "4.1.1";
          tarball = {
            url = "https://registry.npmjs.org/debug/-/debug-4.1.1.tgz";
            sha512 = "pYAIzeRo8J6KPEaJ0VWOh5Pzkbw/RetuzehGM7QRRX5he4fPHx2rdKMB256ehJCkX+XRQm16eZLqLNS8RSZXZw==";
          };
        };
        deep-extend = {
          name = "deep-extend";
          packageName = "deep-extend";
          version = "0.6.0";
          tarball = {
            url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.6.0.tgz";
            sha512 = "LOHxIOaPYdHlJRtCQfDIVZtfw/ufM8+rVj649RIHzcm/vGwQRXFt6OPqIFWsm2XEMrNIEtWR64sY1LEKD2vAOA==";
          };
        };
        delegates = {
          name = "delegates";
          packageName = "delegates";
          version = "1.0.0";
          tarball = {
            url = "https://registry.npmjs.org/delegates/-/delegates-1.0.0.tgz";
            sha1 = "hMbhWbgZBP3KWaDvRM2HDTElD5o=";
          };
        };
        detect-libc = {
          name = "detect-libc";
          packageName = "detect-libc";
          version = "1.0.3";
          bin = {
            detect-libc = "./bin/detect-libc.js";
          };
          tarball = {
            url = "https://registry.npmjs.org/detect-libc/-/detect-libc-1.0.3.tgz";
            sha1 = "+hN8S9aY7fVc1c0CrFWfkaTEups=";
          };
        };
        fs-minipass = {
          name = "fs-minipass";
          packageName = "fs-minipass";
          version = "1.2.5";
          tarball = {
            url = "https://registry.npmjs.org/fs-minipass/-/fs-minipass-1.2.5.tgz";
            sha512 = "JhBl0skXjUPCFH7x6x61gQxrKyXsxB5gcgePLZCwfyCGGsTISMoIeObbrvVeP6Xmyaudw4TT43qV2Gz+iyd2oQ==";
          };
        };
        "fs.realpath" = {
          name = "fs.realpath";
          packageName = "fs.realpath";
          version = "1.0.0";
          tarball = {
            url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
            sha1 = "FQStJSMVjKpA20onh8sBQRmU6k8=";
          };
        };
        gauge = {
          name = "gauge";
          packageName = "gauge";
          version = "2.7.4";
          tarball = {
            url = "https://registry.npmjs.org/gauge/-/gauge-2.7.4.tgz";
            sha1 = "LANAXHU4w51+s3sxcCLjJfsBi/c=";
          };
        };
        glob = {
          name = "glob";
          packageName = "glob";
          version = "7.1.3";
          tarball = {
            url = "https://registry.npmjs.org/glob/-/glob-7.1.3.tgz";
            sha512 = "vcfuiIxogLV4DlGBHIUOwI0IbrJ8HWPc4MU7HzviGeNho/UJDfi6B5p3sHeWIQ0KGIU0Jpxi5ZHxemQfLkkAwQ==";
          };
        };
        has-unicode = {
          name = "has-unicode";
          packageName = "has-unicode";
          version = "2.0.1";
          tarball = {
            url = "https://registry.npmjs.org/has-unicode/-/has-unicode-2.0.1.tgz";
            sha1 = "4Ob+aijPUROIVeCG0Wkedx3iqLk=";
          };
        };
        iconv-lite = {
          name = "iconv-lite";
          packageName = "iconv-lite";
          version = "0.4.24";
          tarball = {
            url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
            sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
          };
        };
        ignore-walk = {
          name = "ignore-walk";
          packageName = "ignore-walk";
          version = "3.0.1";
          tarball = {
            url = "https://registry.npmjs.org/ignore-walk/-/ignore-walk-3.0.1.tgz";
            sha512 = "DTVlMx3IYPe0/JJcYP7Gxg7ttZZu3IInhuEhbchuqneY9wWe5Ojy2mXLBaQFUQmo0AW2r3qG7m1mg86js+gnlQ==";
          };
        };
        inflight = {
          name = "inflight";
          packageName = "inflight";
          version = "1.0.6";
          tarball = {
            url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
            sha1 = "Sb1jMdfQLQwJvJEKEHW6gWW1bfk=";
          };
        };
        inherits = {
          name = "inherits";
          packageName = "inherits";
          version = "2.0.3";
          tarball = {
            url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
            sha1 = "Yzwsg+PaQqUC9SRmAiSA9CCCYd4=";
          };
        };
        ini = {
          name = "ini";
          packageName = "ini";
          version = "1.3.5";
          tarball = {
            url = "https://registry.npmjs.org/ini/-/ini-1.3.5.tgz";
            sha512 = "RZY5huIKCMRWDUqZlEi72f/lmXKMvuszcMBduliQ3nnWbx9X/ZBQO7DijMEYS9EhHBb2qacRUMtC7svLwe0lcw==";
          };
        };
        is-fullwidth-code-point = {
          name = "is-fullwidth-code-point";
          packageName = "is-fullwidth-code-point";
          version = "1.0.0";
          tarball = {
            url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
            sha1 = "754xOG8DGn8NZDr4L95QxFfvAMs=";
          };
        };
        isarray = {
          name = "isarray";
          packageName = "isarray";
          version = "1.0.0";
          tarball = {
            url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
            sha1 = "u5NdSFgsuhaMBoNJV6VKPgcSTxE=";
          };
        };
        minimatch = {
          name = "minimatch";
          packageName = "minimatch";
          version = "3.0.4";
          tarball = {
            url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
            sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
          };
        };
        minimist = {
          name = "minimist";
          packageName = "minimist";
          version = "0.0.8";
          tarball = {
            url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
            sha1 = "hX/Kv8M5fSYluCKCYuhqp6ARsF0=";
          };
        };
        minipass = {
          name = "minipass";
          packageName = "minipass";
          version = "2.3.5";
          tarball = {
            url = "https://registry.npmjs.org/minipass/-/minipass-2.3.5.tgz";
            sha512 = "Gi1W4k059gyRbyVUZQ4mEqLm0YIUiGYfvxhF6SIlk3ui1WVxMTGfGdQ2SInh3PDrRTVvPKgULkpJtT4RH10+VA==";
          };
        };
        minizlib = {
          name = "minizlib";
          packageName = "minizlib";
          version = "1.2.1";
          tarball = {
            url = "https://registry.npmjs.org/minizlib/-/minizlib-1.2.1.tgz";
            sha512 = "7+4oTUOWKg7AuL3vloEWekXY2/D20cevzsrNT2kGWm+39J9hGTCBv8VI5Pm5lXZ/o3/mdR4f8rflAPhnQb8mPA==";
          };
        };
        mkdirp = {
          name = "mkdirp";
          packageName = "mkdirp";
          version = "0.5.1";
          bin = {
            mkdirp = "bin/cmd.js";
          };
          tarball = {
            url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
            sha1 = "MAV0OOrGz3+MR2fzhkjWaX11yQM=";
          };
        };
        ms = {
          name = "ms";
          packageName = "ms";
          version = "2.1.1";
          tarball = {
            url = "https://registry.npmjs.org/ms/-/ms-2.1.1.tgz";
            sha512 = "tgp+dl5cGk28utYktBsrFqA7HKgrhgPsg6Z/EfhWI4gl1Hwq8B/GmY/0oXZ6nF8hDVesS/FpnYaD/kOWhYQvyg==";
          };
        };
        nan = {
          name = "nan";
          packageName = "nan";
          version = "2.13.1";
          tarball = {
            url = "https://registry.npmjs.org/nan/-/nan-2.13.1.tgz";
            sha512 = "I6YB/YEuDeUZMmhscXKxGgZlFnhsn5y0hgOZBadkzfTRrZBtJDZeg6eQf7PYMIEclwmorTKK8GztsyOUSVBREA==";
          };
        };
        needle = {
          name = "needle";
          packageName = "needle";
          version = "2.3.0";
          bin = {
            needle = "./bin/needle";
          };
          tarball = {
            url = "https://registry.npmjs.org/needle/-/needle-2.3.0.tgz";
            sha512 = "QBZu7aAFR0522EyaXZM0FZ9GLpq6lvQ3uq8gteiDUp7wKdy0lSd2hPlgFwVuW1CBkfEs9PfDQsQzZghLs/psdg==";
          };
        };
        node-pre-gyp = {
          name = "node-pre-gyp";
          packageName = "node-pre-gyp";
          version = "0.12.0";
          bin = {
            node-pre-gyp = "./bin/node-pre-gyp";
          };
          tarball = {
            url = "https://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.12.0.tgz";
            sha512 = "4KghwV8vH5k+g2ylT+sLTjy5wmUOb9vPhnM8NHvRf9dHmnW/CndrFXy2aRPaPST6dugXSdHXfeaHQm77PIz/1A==";
          };
        };
        nopt = {
          name = "nopt";
          packageName = "nopt";
          version = "4.0.1";
          bin = {
            nopt = "./bin/nopt.js";
          };
          tarball = {
            url = "https://registry.npmjs.org/nopt/-/nopt-4.0.1.tgz";
            sha1 = "0NRoWv1UFRk8jHUFYC0NF81kR00=";
          };
        };
        npm-bundled = {
          name = "npm-bundled";
          packageName = "npm-bundled";
          version = "1.0.6";
          tarball = {
            url = "https://registry.npmjs.org/npm-bundled/-/npm-bundled-1.0.6.tgz";
            sha512 = "8/JCaftHwbd//k6y2rEWp6k1wxVfpFzB6t1p825+cUb7Ym2XQfhwIC5KwhrvzZRJu+LtDE585zVaS32+CGtf0g==";
          };
        };
        npm-packlist = {
          name = "npm-packlist";
          packageName = "npm-packlist";
          version = "1.4.1";
          tarball = {
            url = "https://registry.npmjs.org/npm-packlist/-/npm-packlist-1.4.1.tgz";
            sha512 = "+TcdO7HJJ8peiiYhvPxsEDhF3PJFGUGRcFsGve3vxvxdcpO2Z4Z7rkosRM0kWj6LfbK/P0gu3dzk5RU1ffvFcw==";
          };
        };
        npmlog = {
          name = "npmlog";
          packageName = "npmlog";
          version = "4.1.2";
          tarball = {
            url = "https://registry.npmjs.org/npmlog/-/npmlog-4.1.2.tgz";
            sha512 = "2uUqazuKlTaSI/dC8AzicUck7+IrEaOnN/e0jd3Xtt1KcGpwx30v50mL7oPyr/h9bL3E4aZccVwpwP+5W9Vjkg==";
          };
        };
        number-is-nan = {
          name = "number-is-nan";
          packageName = "number-is-nan";
          version = "1.0.1";
          tarball = {
            url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
            sha1 = "CXtgK1NCKlIsGvuHkDGDNpQaAR0=";
          };
        };
        object-assign = {
          name = "object-assign";
          packageName = "object-assign";
          version = "4.1.1";
          tarball = {
            url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
            sha1 = "IQmtx5ZYh8/AXLvUQsrIv7s2CGM=";
          };
        };
        once = {
          name = "once";
          packageName = "once";
          version = "1.4.0";
          tarball = {
            url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
            sha1 = "WDsap3WWHUsROsF9nFC6753Xa9E=";
          };
        };
        os-homedir = {
          name = "os-homedir";
          packageName = "os-homedir";
          version = "1.0.2";
          tarball = {
            url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
            sha1 = "/7xJiDNuDoM94MFox+8VISGqf7M=";
          };
        };
        os-tmpdir = {
          name = "os-tmpdir";
          packageName = "os-tmpdir";
          version = "1.0.2";
          tarball = {
            url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
            sha1 = "u+Z0BseaqFxc/sdm/lc0VV36EnQ=";
          };
        };
        osenv = {
          name = "osenv";
          packageName = "osenv";
          version = "0.1.5";
          tarball = {
            url = "https://registry.npmjs.org/osenv/-/osenv-0.1.5.tgz";
            sha512 = "0CWcCECdMVc2Rw3U5w9ZjqX6ga6ubk1xDVKxtBQPK7wis/0F2r9T6k4ydGYhecl7YUBxBVxhL5oisPsNxAPe2g==";
          };
        };
        path-is-absolute = {
          name = "path-is-absolute";
          packageName = "path-is-absolute";
          version = "1.0.1";
          tarball = {
            url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
            sha1 = "F0uSaHNVNP+8es5r9TpanhtcX18=";
          };
        };
        process-nextick-args = {
          name = "process-nextick-args";
          packageName = "process-nextick-args";
          version = "2.0.0";
          tarball = {
            url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz";
            sha512 = "MtEC1TqN0EU5nephaJ4rAtThHtC86dNN9qCuEhtshvpVBkAW5ZO7BASN9REnF9eoXGcRub+pFuKEpOHE+HbEMw==";
          };
        };
        rc = {
          name = "rc";
          packageName = "rc";
          version = "1.2.8";
          bin = {
            rc = "./cli.js";
          };
          tarball = {
            url = "https://registry.npmjs.org/rc/-/rc-1.2.8.tgz";
            sha512 = "y3bGgqKj3QBdxLbLkomlohkvsA8gdAiUQlSBJnBhfn+BPxg4bc62d8TcBW15wavDfgexCgccckhcZvywyQYPOw==";
          };
          privateDependencies = {
            minimist = {
              name = "minimist";
              packageName = "minimist";
              version = "1.2.0";
              tarball = {
                url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
                sha1 = "o1AIsg9BOD7sH7kU9M1d95omQoQ=";
              };
            };
          };
        };
        readable-stream = {
          name = "readable-stream";
          packageName = "readable-stream";
          version = "2.3.6";
          tarball = {
            url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz";
            sha512 = "tQtKA9WIAhBF3+VLAseyMqZeBjW0AHJoxOtYqSUZNJxauErmLbVm2FW1y+J/YA9dUrAC39ITejlZWhVIwawkKw==";
          };
        };
        rimraf = {
          name = "rimraf";
          packageName = "rimraf";
          version = "2.6.3";
          bin = {
            rimraf = "./bin.js";
          };
          tarball = {
            url = "https://registry.npmjs.org/rimraf/-/rimraf-2.6.3.tgz";
            sha512 = "mwqeW5XsA2qAejG46gYdENaxXjx9onRNCfn7L0duuP4hCuTIi/QO7PDK07KJfp1d+izWPrzEJDcSqBa0OZQriA==";
          };
        };
        safe-buffer = {
          name = "safe-buffer";
          packageName = "safe-buffer";
          version = "5.1.2";
          tarball = {
            url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
            sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
          };
        };
        safer-buffer = {
          name = "safer-buffer";
          packageName = "safer-buffer";
          version = "2.1.2";
          tarball = {
            url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
            sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
          };
        };
        sax = {
          name = "sax";
          packageName = "sax";
          version = "1.2.4";
          tarball = {
            url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
            sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
          };
        };
        semver = {
          name = "semver";
          packageName = "semver";
          version = "5.7.0";
          bin = {
            semver = "./bin/semver";
          };
          tarball = {
            url = "https://registry.npmjs.org/semver/-/semver-5.7.0.tgz";
            sha512 = "Ya52jSX2u7QKghxeoFGpLwCtGlt7j0oY9DYb5apt9nPlJ42ID+ulTXESnt/qAQcoSERyZ5sl3LDIOw0nAn/5DA==";
          };
        };
        set-blocking = {
          name = "set-blocking";
          packageName = "set-blocking";
          version = "2.0.0";
          tarball = {
            url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
            sha1 = "BF+XgtARrppoA93TgrJDkrPYkPc=";
          };
        };
        signal-exit = {
          name = "signal-exit";
          packageName = "signal-exit";
          version = "3.0.2";
          tarball = {
            url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz";
            sha1 = "tf3AjxKH6hF4Yo5BXiUTK3NkbG0=";
          };
        };
        string-width = {
          name = "string-width";
          packageName = "string-width";
          version = "1.0.2";
          tarball = {
            url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
            sha1 = "EYvfW4zcUaKn5w0hHgfisLmxB9M=";
          };
        };
        string_decoder = {
          name = "string_decoder";
          packageName = "string_decoder";
          version = "1.1.1";
          tarball = {
            url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
            sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
          };
        };
        strip-ansi = {
          name = "strip-ansi";
          packageName = "strip-ansi";
          version = "3.0.1";
          tarball = {
            url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
            sha1 = "ajhfuIU9lS1f8F0Oiq+UJ43GPc8=";
          };
        };
        strip-json-comments = {
          name = "strip-json-comments";
          packageName = "strip-json-comments";
          version = "2.0.1";
          tarball = {
            url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-2.0.1.tgz";
            sha1 = "PFMZQukIwml8DsNEhYwobHygpgo=";
          };
        };
        tar = {
          name = "tar";
          packageName = "tar";
          version = "4.4.8";
          tarball = {
            url = "https://registry.npmjs.org/tar/-/tar-4.4.8.tgz";
            sha512 = "LzHF64s5chPQQS0IYBn9IN5h3i98c12bo4NCO7e0sGM2llXQ3p2FGC5sdENN4cTW48O915Sh+x+EXx7XW96xYQ==";
          };
        };
        util-deprecate = {
          name = "util-deprecate";
          packageName = "util-deprecate";
          version = "1.0.2";
          tarball = {
            url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
            sha1 = "RQ1Nyfpw3nMnYvvS1KKJgUGaDM8=";
          };
        };
        wide-align = {
          name = "wide-align";
          packageName = "wide-align";
          version = "1.1.3";
          tarball = {
            url = "https://registry.npmjs.org/wide-align/-/wide-align-1.1.3.tgz";
            sha512 = "QGkOQc8XL6Bt5PwnsExKBPuMKBxnGxWWW3fU55Xt4feHozMUhdUMaBCk290qpm/wG5u/RSKzwdAC4i51YigihA==";
          };
        };
        wrappy = {
          name = "wrappy";
          packageName = "wrappy";
          version = "1.0.2";
          tarball = {
            url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
            sha1 = "tSQ9jz7BqjXxNkYFvA0QNuMKtp8=";
          };
        };
        yallist = {
          name = "yallist";
          packageName = "yallist";
          version = "3.0.3";
          tarball = {
            url = "https://registry.npmjs.org/yallist/-/yallist-3.0.3.tgz";
            sha512 = "S+Zk8DEWE6oKpV+vI3qWkaK+jSbIK86pCwe2IF/xwIpQ8jEuxpw9NyaGjmp9+BoJv5FV2piqCDcoCtStppiq2A==";
          };
        };
      };
    };
    brace-expansion = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      tarball = {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    camelcase = {
      name = "camelcase";
      packageName = "camelcase";
      version = "5.3.0";
      tarball = {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-5.3.0.tgz";
        sha512 = "Y05ICatFYPAfykDIB7VdwSJ0LUl1yq/BwO2OpyGGLjiRe1fgzTwVypPiWnzkGFOVFHXrCXUNBl86bpjBhZWSJg==";
      };
    };
    chownr = {
      name = "chownr";
      packageName = "chownr";
      version = "1.1.1";
      tarball = {
        url = "https://registry.npmjs.org/chownr/-/chownr-1.1.1.tgz";
        sha512 = "j38EvO5+LHX84jlo6h4UzmOwi0UgW61WRyPtJz4qaadK5eY3BTS5TY/S1Stc3Uk2lIM6TPevAlULiEJwie860g==";
      };
    };
    cliui = {
      name = "cliui";
      packageName = "cliui";
      version = "4.1.0";
      tarball = {
        url = "https://registry.npmjs.org/cliui/-/cliui-4.1.0.tgz";
        sha512 = "4FG+RSG9DL7uEwRUZXZn3SS34DiDPfzP0VOiEwtUWlE+AR2EIg+hSyvrIgUUfhdgR/UkAeW2QHgeP+hWrXs7jQ==";
      };
      privateDependencies = {
        string-width = {
          name = "string-width";
          packageName = "string-width";
          version = "2.1.1";
          tarball = {
            url = "https://registry.npmjs.org/string-width/-/string-width-2.1.1.tgz";
            sha512 = "nOqH59deCq9SRHlxq1Aw85Jnt4w6KvLKqWVik6oA9ZklXLNIOlqg4F2yrT1MVaTjAqvVwdfeZ7w7aCvJD7ugkw==";
          };
        };
      };
    };
    code-point-at = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.1.0";
      tarball = {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.1.0.tgz";
        sha1 = "DQcLTQQ6W+ozovGkDi7bPZpMz3c=";
      };
    };
    concat-map = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      tarball = {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "2Klr13/Wjfd5OnMDajug1UBdR3s=";
      };
    };
    console-control-strings = {
      name = "console-control-strings";
      packageName = "console-control-strings";
      version = "1.1.0";
      tarball = {
        url = "https://registry.npmjs.org/console-control-strings/-/console-control-strings-1.1.0.tgz";
        sha1 = "PXz0Rk22RG6mRL9LOVB/mFEAjo4=";
      };
    };
    core-util-is = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      tarball = {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "tf1UIgqivFq1eqtxQMlAdUUDwac=";
      };
    };
    cross-spawn = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "6.0.5";
      tarball = {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-6.0.5.tgz";
        sha512 = "eTVLrBSt7fjbDygz805pMnstIs2VTBNkRm0qxZd+M7A5XDdxVRWO5MxGBXZhjY4cqLYLdtrGqRf8mBPmzwSpWQ==";
      };
    };
    debug = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      tarball = {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    decamelize = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      tarball = {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "9lNNFRSCabIDUue+4m9QH5oZEpA=";
      };
    };
    deep-extend = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.6.0";
      tarball = {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.6.0.tgz";
        sha512 = "LOHxIOaPYdHlJRtCQfDIVZtfw/ufM8+rVj649RIHzcm/vGwQRXFt6OPqIFWsm2XEMrNIEtWR64sY1LEKD2vAOA==";
      };
    };
    delegates = {
      name = "delegates";
      packageName = "delegates";
      version = "1.0.0";
      tarball = {
        url = "https://registry.npmjs.org/delegates/-/delegates-1.0.0.tgz";
        sha1 = "hMbhWbgZBP3KWaDvRM2HDTElD5o=";
      };
    };
    detect-libc = {
      name = "detect-libc";
      packageName = "detect-libc";
      version = "1.0.3";
      bin = {
        detect-libc = "./bin/detect-libc.js";
      };
      tarball = {
        url = "https://registry.npmjs.org/detect-libc/-/detect-libc-1.0.3.tgz";
        sha1 = "+hN8S9aY7fVc1c0CrFWfkaTEups=";
      };
    };
    emoji-regex = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "7.0.3";
      tarball = {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-7.0.3.tgz";
        sha512 = "CwBLREIQ7LvYFB0WyRvwhq5N5qPhc6PMjD6bYggFlI5YyDgl+0vxq5VHbMOFqLg7hfWzmu8T5Z1QofhmTIhItA==";
      };
    };
    end-of-stream = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.1";
      tarball = {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.1.tgz";
        sha512 = "1MkrZNvWTKCaigbn+W15elq2BB/L22nqrSY5DKlo3X6+vclJm8Bb5djXJBmEX6fS3+zCh/F4VBK5Z2KxJt4s2Q==";
      };
    };
    execa = {
      name = "execa";
      packageName = "execa";
      version = "1.0.0";
      tarball = {
        url = "https://registry.npmjs.org/execa/-/execa-1.0.0.tgz";
        sha512 = "adbxcyWV46qiHyvSp50TKt05tB4tK3HcmF7/nxfAdhnox83seTDbwnaqKO4sXRy7roHAIFqJP/Rw/AuEbX61LA==";
      };
    };
    find-up = {
      name = "find-up";
      packageName = "find-up";
      version = "3.0.0";
      tarball = {
        url = "https://registry.npmjs.org/find-up/-/find-up-3.0.0.tgz";
        sha512 = "1yD6RmLI1XBfxugvORwlck6f75tYL+iR0jqwsOrOxMZyGYqUuDhJ0l4AXdO1iX/FTs9cBAMEk1gWSEx1kSbylg==";
      };
    };
    fs-minipass = {
      name = "fs-minipass";
      packageName = "fs-minipass";
      version = "1.2.5";
      tarball = {
        url = "https://registry.npmjs.org/fs-minipass/-/fs-minipass-1.2.5.tgz";
        sha512 = "JhBl0skXjUPCFH7x6x61gQxrKyXsxB5gcgePLZCwfyCGGsTISMoIeObbrvVeP6Xmyaudw4TT43qV2Gz+iyd2oQ==";
      };
    };
    "fs.realpath" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      tarball = {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "FQStJSMVjKpA20onh8sBQRmU6k8=";
      };
    };
    gauge = {
      name = "gauge";
      packageName = "gauge";
      version = "2.7.4";
      tarball = {
        url = "https://registry.npmjs.org/gauge/-/gauge-2.7.4.tgz";
        sha1 = "LANAXHU4w51+s3sxcCLjJfsBi/c=";
      };
      privateDependencies = {
        ansi-regex = {
          name = "ansi-regex";
          packageName = "ansi-regex";
          version = "2.1.1";
          tarball = {
            url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
            sha1 = "w7M6te42DYbg5ijwRorn7yfWVN8=";
          };
        };
        is-fullwidth-code-point = {
          name = "is-fullwidth-code-point";
          packageName = "is-fullwidth-code-point";
          version = "1.0.0";
          tarball = {
            url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
            sha1 = "754xOG8DGn8NZDr4L95QxFfvAMs=";
          };
        };
        string-width = {
          name = "string-width";
          packageName = "string-width";
          version = "1.0.2";
          tarball = {
            url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
            sha1 = "EYvfW4zcUaKn5w0hHgfisLmxB9M=";
          };
        };
        strip-ansi = {
          name = "strip-ansi";
          packageName = "strip-ansi";
          version = "3.0.1";
          tarball = {
            url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
            sha1 = "ajhfuIU9lS1f8F0Oiq+UJ43GPc8=";
          };
        };
      };
    };
    get-caller-file = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "2.0.5";
      hasPrepareHooks = true;
      tarball = {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz";
        sha512 = "DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==";
      };
    };
    get-stream = {
      name = "get-stream";
      packageName = "get-stream";
      version = "4.1.0";
      tarball = {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-4.1.0.tgz";
        sha512 = "GMat4EJ5161kIy2HevLlr4luNjBgvmj413KaQA7jt4V8B4RDsfpHk7WQ9GVqfYyyx8OS/L66Kox+rJRNklLK7w==";
      };
    };
    glob = {
      name = "glob";
      packageName = "glob";
      version = "7.1.3";
      tarball = {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.3.tgz";
        sha512 = "vcfuiIxogLV4DlGBHIUOwI0IbrJ8HWPc4MU7HzviGeNho/UJDfi6B5p3sHeWIQ0KGIU0Jpxi5ZHxemQfLkkAwQ==";
      };
    };
    has-unicode = {
      name = "has-unicode";
      packageName = "has-unicode";
      version = "2.0.1";
      tarball = {
        url = "https://registry.npmjs.org/has-unicode/-/has-unicode-2.0.1.tgz";
        sha1 = "4Ob+aijPUROIVeCG0Wkedx3iqLk=";
      };
    };
    iconv-lite = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.24";
      tarball = {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
        sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
      };
    };
    ignore-walk = {
      name = "ignore-walk";
      packageName = "ignore-walk";
      version = "3.0.1";
      tarball = {
        url = "https://registry.npmjs.org/ignore-walk/-/ignore-walk-3.0.1.tgz";
        sha512 = "DTVlMx3IYPe0/JJcYP7Gxg7ttZZu3IInhuEhbchuqneY9wWe5Ojy2mXLBaQFUQmo0AW2r3qG7m1mg86js+gnlQ==";
      };
    };
    inflight = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      tarball = {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "Sb1jMdfQLQwJvJEKEHW6gWW1bfk=";
      };
    };
    inherits = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      tarball = {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "Yzwsg+PaQqUC9SRmAiSA9CCCYd4=";
      };
    };
    ini = {
      name = "ini";
      packageName = "ini";
      version = "1.3.5";
      tarball = {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.5.tgz";
        sha512 = "RZY5huIKCMRWDUqZlEi72f/lmXKMvuszcMBduliQ3nnWbx9X/ZBQO7DijMEYS9EhHBb2qacRUMtC7svLwe0lcw==";
      };
    };
    invert-kv = {
      name = "invert-kv";
      packageName = "invert-kv";
      version = "2.0.0";
      tarball = {
        url = "https://registry.npmjs.org/invert-kv/-/invert-kv-2.0.0.tgz";
        sha512 = "wPVv/y/QQ/Uiirj/vh3oP+1Ww+AWehmi1g5fFWGPF6IpCBCDVrhgHRMvrLfdYcwDh3QJbGXDW4JAuzxElLSqKA==";
      };
    };
    is-fullwidth-code-point = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "2.0.0";
      tarball = {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-2.0.0.tgz";
        sha1 = "o7MKXE8ZkYMWeqq5O+764937ZU8=";
      };
    };
    is-stream = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      tarball = {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "EtSj3U5o4Lec6428hBc66A2RykQ=";
      };
    };
    isarray = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      tarball = {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "u5NdSFgsuhaMBoNJV6VKPgcSTxE=";
      };
    };
    isexe = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      tarball = {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "6PvzdNxVb/iUehDcsFctYz8s+hA=";
      };
    };
    lcid = {
      name = "lcid";
      packageName = "lcid";
      version = "2.0.0";
      tarball = {
        url = "https://registry.npmjs.org/lcid/-/lcid-2.0.0.tgz";
        sha512 = "avPEb8P8EGnwXKClwsNUgryVjllcRqtMYa49NTsbQagYuT1DcXnl1915oxWjoyGrXR6zH/Y0Zc96xWsPcoDKeA==";
      };
    };
    locate-path = {
      name = "locate-path";
      packageName = "locate-path";
      version = "3.0.0";
      tarball = {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-3.0.0.tgz";
        sha512 = "7AO748wWnIhNqAuaty2ZWHkQHRSNfPVIsPIfwEOWO22AmaoVrWavlOcMR5nzTLNYvp36X220/maaRsrec1G65A==";
      };
    };
    map-age-cleaner = {
      name = "map-age-cleaner";
      packageName = "map-age-cleaner";
      version = "0.1.3";
      tarball = {
        url = "https://registry.npmjs.org/map-age-cleaner/-/map-age-cleaner-0.1.3.tgz";
        sha512 = "bJzx6nMoP6PDLPBFmg7+xRKeFZvFboMrGlxmNj9ClvX53KrmvM5bXFXEWjbz4cz1AFn+jWJ9z/DJSz7hrs0w3w==";
      };
    };
    mem = {
      name = "mem";
      packageName = "mem";
      version = "4.3.0";
      tarball = {
        url = "https://registry.npmjs.org/mem/-/mem-4.3.0.tgz";
        sha512 = "qX2bG48pTqYRVmDB37rn/6PT7LcR8T7oAX3bf99u1Tt1nzxYfxkgqDwUwolPlXweM0XzBOBFzSx4kfp7KP1s/w==";
      };
    };
    mimic-fn = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "2.1.0";
      tarball = {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
        sha512 = "OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
      };
    };
    minimatch = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      tarball = {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    minimist = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      tarball = {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "hX/Kv8M5fSYluCKCYuhqp6ARsF0=";
      };
    };
    minipass = {
      name = "minipass";
      packageName = "minipass";
      version = "2.3.5";
      tarball = {
        url = "https://registry.npmjs.org/minipass/-/minipass-2.3.5.tgz";
        sha512 = "Gi1W4k059gyRbyVUZQ4mEqLm0YIUiGYfvxhF6SIlk3ui1WVxMTGfGdQ2SInh3PDrRTVvPKgULkpJtT4RH10+VA==";
      };
    };
    minizlib = {
      name = "minizlib";
      packageName = "minizlib";
      version = "1.2.1";
      tarball = {
        url = "https://registry.npmjs.org/minizlib/-/minizlib-1.2.1.tgz";
        sha512 = "7+4oTUOWKg7AuL3vloEWekXY2/D20cevzsrNT2kGWm+39J9hGTCBv8VI5Pm5lXZ/o3/mdR4f8rflAPhnQb8mPA==";
      };
    };
    mkdirp = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      bin = {
        mkdirp = "bin/cmd.js";
      };
      tarball = {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "MAV0OOrGz3+MR2fzhkjWaX11yQM=";
      };
    };
    ms = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      tarball = {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "VgiurfwAvmwpAd9fmGF4jeDVl8g=";
      };
    };
    nan = {
      name = "nan";
      packageName = "nan";
      version = "2.13.1";
      tarball = {
        url = "https://registry.npmjs.org/nan/-/nan-2.13.1.tgz";
        sha512 = "I6YB/YEuDeUZMmhscXKxGgZlFnhsn5y0hgOZBadkzfTRrZBtJDZeg6eQf7PYMIEclwmorTKK8GztsyOUSVBREA==";
      };
    };
    needle = {
      name = "needle";
      packageName = "needle";
      version = "2.2.4";
      bin = {
        needle = "./bin/needle";
      };
      tarball = {
        url = "https://registry.npmjs.org/needle/-/needle-2.2.4.tgz";
        sha512 = "HyoqEb4wr/rsoaIDfTH2aVL9nWtQqba2/HvMv+++m8u0dz808MaagKILxtfeSN7QU7nvbQ79zk3vYOJp9zsNEA==";
      };
    };
    nice-try = {
      name = "nice-try";
      packageName = "nice-try";
      version = "1.0.5";
      tarball = {
        url = "https://registry.npmjs.org/nice-try/-/nice-try-1.0.5.tgz";
        sha512 = "1nh45deeb5olNY7eX82BkPO7SSxR5SSYJiPTrTdFUVYwAl8CKMA5N9PjTYkHiRjisVcxcQ1HXdLhx2qxxJzLNQ==";
      };
    };
    node-pre-gyp = {
      name = "node-pre-gyp";
      packageName = "node-pre-gyp";
      version = "0.12.0";
      bin = {
        node-pre-gyp = "./bin/node-pre-gyp";
      };
      tarball = {
        url = "https://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.12.0.tgz";
        sha512 = "4KghwV8vH5k+g2ylT+sLTjy5wmUOb9vPhnM8NHvRf9dHmnW/CndrFXy2aRPaPST6dugXSdHXfeaHQm77PIz/1A==";
      };
    };
    nopt = {
      name = "nopt";
      packageName = "nopt";
      version = "4.0.1";
      bin = {
        nopt = "./bin/nopt.js";
      };
      tarball = {
        url = "https://registry.npmjs.org/nopt/-/nopt-4.0.1.tgz";
        sha1 = "0NRoWv1UFRk8jHUFYC0NF81kR00=";
      };
    };
    npm-bundled = {
      name = "npm-bundled";
      packageName = "npm-bundled";
      version = "1.0.6";
      tarball = {
        url = "https://registry.npmjs.org/npm-bundled/-/npm-bundled-1.0.6.tgz";
        sha512 = "8/JCaftHwbd//k6y2rEWp6k1wxVfpFzB6t1p825+cUb7Ym2XQfhwIC5KwhrvzZRJu+LtDE585zVaS32+CGtf0g==";
      };
    };
    npm-packlist = {
      name = "npm-packlist";
      packageName = "npm-packlist";
      version = "1.4.1";
      tarball = {
        url = "https://registry.npmjs.org/npm-packlist/-/npm-packlist-1.4.1.tgz";
        sha512 = "+TcdO7HJJ8peiiYhvPxsEDhF3PJFGUGRcFsGve3vxvxdcpO2Z4Z7rkosRM0kWj6LfbK/P0gu3dzk5RU1ffvFcw==";
      };
    };
    npm-run-path = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "2.0.2";
      tarball = {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-2.0.2.tgz";
        sha1 = "NakjLfo11wZ7TLLd8jV7GHFTbF8=";
      };
    };
    npmlog = {
      name = "npmlog";
      packageName = "npmlog";
      version = "4.1.2";
      tarball = {
        url = "https://registry.npmjs.org/npmlog/-/npmlog-4.1.2.tgz";
        sha512 = "2uUqazuKlTaSI/dC8AzicUck7+IrEaOnN/e0jd3Xtt1KcGpwx30v50mL7oPyr/h9bL3E4aZccVwpwP+5W9Vjkg==";
      };
    };
    number-is-nan = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      tarball = {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "CXtgK1NCKlIsGvuHkDGDNpQaAR0=";
      };
    };
    object-assign = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      tarball = {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "IQmtx5ZYh8/AXLvUQsrIv7s2CGM=";
      };
    };
    once = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      tarball = {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "WDsap3WWHUsROsF9nFC6753Xa9E=";
      };
    };
    os-homedir = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.2";
      tarball = {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
        sha1 = "/7xJiDNuDoM94MFox+8VISGqf7M=";
      };
    };
    os-locale = {
      name = "os-locale";
      packageName = "os-locale";
      version = "3.1.0";
      tarball = {
        url = "https://registry.npmjs.org/os-locale/-/os-locale-3.1.0.tgz";
        sha512 = "Z8l3R4wYWM40/52Z+S265okfFj8Kt2cC2MKY+xNi3kFs+XGI7WXu/I309QQQYbRW4ijiZ+yxs9pqEhJh0DqW3Q==";
      };
    };
    os-tmpdir = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      tarball = {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "u+Z0BseaqFxc/sdm/lc0VV36EnQ=";
      };
    };
    osenv = {
      name = "osenv";
      packageName = "osenv";
      version = "0.1.5";
      tarball = {
        url = "https://registry.npmjs.org/osenv/-/osenv-0.1.5.tgz";
        sha512 = "0CWcCECdMVc2Rw3U5w9ZjqX6ga6ubk1xDVKxtBQPK7wis/0F2r9T6k4ydGYhecl7YUBxBVxhL5oisPsNxAPe2g==";
      };
    };
    p-defer = {
      name = "p-defer";
      packageName = "p-defer";
      version = "1.0.0";
      tarball = {
        url = "https://registry.npmjs.org/p-defer/-/p-defer-1.0.0.tgz";
        sha1 = "n26xgvbJqozXQwBKfU+WsZaw+ww=";
      };
    };
    p-finally = {
      name = "p-finally";
      packageName = "p-finally";
      version = "1.0.0";
      tarball = {
        url = "https://registry.npmjs.org/p-finally/-/p-finally-1.0.0.tgz";
        sha1 = "P7z7FbiZpEEjs0ttzBi3JDNqLK4=";
      };
    };
    p-is-promise = {
      name = "p-is-promise";
      packageName = "p-is-promise";
      version = "2.0.0";
      tarball = {
        url = "https://registry.npmjs.org/p-is-promise/-/p-is-promise-2.0.0.tgz";
        sha512 = "pzQPhYMCAgLAKPWD2jC3Se9fEfrD9npNos0y150EeqZll7akhEgGhTW/slB6lHku8AvYGiJ+YJ5hfHKePPgFWg==";
      };
    };
    p-limit = {
      name = "p-limit";
      packageName = "p-limit";
      version = "2.2.0";
      tarball = {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-2.2.0.tgz";
        sha512 = "pZbTJpoUsCzV48Mc9Nh51VbwO0X9cuPFE8gYwx9BTCt9SF8/b7Zljd2fVgOxhIF/HDTKgpVzs+GPhyKfjLLFRQ==";
      };
    };
    p-locate = {
      name = "p-locate";
      packageName = "p-locate";
      version = "3.0.0";
      tarball = {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-3.0.0.tgz";
        sha512 = "x+12w/To+4GFfgJhBEpiDcLozRJGegY+Ei7/z0tSLkMmxGZNybVMSfWj9aJn8Z5Fc7dBUNJOOVgPv2H7IwulSQ==";
      };
    };
    p-try = {
      name = "p-try";
      packageName = "p-try";
      version = "2.2.0";
      tarball = {
        url = "https://registry.npmjs.org/p-try/-/p-try-2.2.0.tgz";
        sha512 = "R4nPAVTAU0B9D35/Gk3uJf/7XYbQcyohSKdvAxIRSNghFl4e71hVoGnBNQz9cWaXxO2I10KTC+3jMdvvoKw6dQ==";
      };
    };
    path-exists = {
      name = "path-exists";
      packageName = "path-exists";
      version = "3.0.0";
      tarball = {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-3.0.0.tgz";
        sha1 = "zg6+ql94yxiSXqfYENe1mwEP1RU=";
      };
    };
    path-is-absolute = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      tarball = {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "F0uSaHNVNP+8es5r9TpanhtcX18=";
      };
    };
    path-key = {
      name = "path-key";
      packageName = "path-key";
      version = "2.0.1";
      tarball = {
        url = "https://registry.npmjs.org/path-key/-/path-key-2.0.1.tgz";
        sha1 = "QRyttXTFoUDTpLGRDUDYDMn0C0A=";
      };
    };
    process-nextick-args = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.0";
      tarball = {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz";
        sha512 = "MtEC1TqN0EU5nephaJ4rAtThHtC86dNN9qCuEhtshvpVBkAW5ZO7BASN9REnF9eoXGcRub+pFuKEpOHE+HbEMw==";
      };
    };
    pump = {
      name = "pump";
      packageName = "pump";
      version = "3.0.0";
      tarball = {
        url = "https://registry.npmjs.org/pump/-/pump-3.0.0.tgz";
        sha512 = "LwZy+p3SFs1Pytd/jYct4wpv49HiYCqd9Rlc5ZVdk0V+8Yzv6jR5Blk3TRmPL1ft69TxP0IMZGJ+WPFU2BFhww==";
      };
    };
    rc = {
      name = "rc";
      packageName = "rc";
      version = "1.2.8";
      bin = {
        rc = "./cli.js";
      };
      tarball = {
        url = "https://registry.npmjs.org/rc/-/rc-1.2.8.tgz";
        sha512 = "y3bGgqKj3QBdxLbLkomlohkvsA8gdAiUQlSBJnBhfn+BPxg4bc62d8TcBW15wavDfgexCgccckhcZvywyQYPOw==";
      };
      privateDependencies = {
        minimist = {
          name = "minimist";
          packageName = "minimist";
          version = "1.2.0";
          tarball = {
            url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
            sha1 = "o1AIsg9BOD7sH7kU9M1d95omQoQ=";
          };
        };
      };
    };
    readable-stream = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.6";
      tarball = {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz";
        sha512 = "tQtKA9WIAhBF3+VLAseyMqZeBjW0AHJoxOtYqSUZNJxauErmLbVm2FW1y+J/YA9dUrAC39ITejlZWhVIwawkKw==";
      };
    };
    require-directory = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      tarball = {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha1 = "jGStX9MNqxyXbiNE/+f3kqam30I=";
      };
    };
    require-main-filename = {
      name = "require-main-filename";
      packageName = "require-main-filename";
      version = "2.0.0";
      tarball = {
        url = "https://registry.npmjs.org/require-main-filename/-/require-main-filename-2.0.0.tgz";
        sha512 = "NKN5kMDylKuldxYLSUfrbo5Tuzh4hd+2E8NPPX02mZtn1VuREQToYe/ZdlJy+J3uCpfaiGF05e7B8W0iXbQHmg==";
      };
    };
    rimraf = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.6.3";
      bin = {
        rimraf = "./bin.js";
      };
      tarball = {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.6.3.tgz";
        sha512 = "mwqeW5XsA2qAejG46gYdENaxXjx9onRNCfn7L0duuP4hCuTIi/QO7PDK07KJfp1d+izWPrzEJDcSqBa0OZQriA==";
      };
    };
    safe-buffer = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      tarball = {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    safer-buffer = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      tarball = {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    sax = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      tarball = {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    semver = {
      name = "semver";
      packageName = "semver";
      version = "5.7.0";
      bin = {
        semver = "./bin/semver";
      };
      tarball = {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.0.tgz";
        sha512 = "Ya52jSX2u7QKghxeoFGpLwCtGlt7j0oY9DYb5apt9nPlJ42ID+ulTXESnt/qAQcoSERyZ5sl3LDIOw0nAn/5DA==";
      };
    };
    set-blocking = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      tarball = {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "BF+XgtARrppoA93TgrJDkrPYkPc=";
      };
    };
    shebang-command = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "1.2.0";
      tarball = {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-1.2.0.tgz";
        sha1 = "RKrGW2lbAzmJaMOfNj/uXer98eo=";
      };
    };
    shebang-regex = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "1.0.0";
      tarball = {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-1.0.0.tgz";
        sha1 = "2kL0l0DAtC2yypcoVxyxkMmO/qM=";
      };
    };
    signal-exit = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.2";
      tarball = {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz";
        sha1 = "tf3AjxKH6hF4Yo5BXiUTK3NkbG0=";
      };
    };
    string-width = {
      name = "string-width";
      packageName = "string-width";
      version = "3.1.0";
      tarball = {
        url = "https://registry.npmjs.org/string-width/-/string-width-3.1.0.tgz";
        sha512 = "vafcv6KjVZKSgz06oM/H6GDBrAtz8vdhQakGjFIvNrHA6y3HCF1CInLy+QLq8dTJPQ1b+KDUqDFctkdRW44e1w==";
      };
      privateDependencies = {
        ansi-regex = {
          name = "ansi-regex";
          packageName = "ansi-regex";
          version = "4.1.0";
          tarball = {
            url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-4.1.0.tgz";
            sha512 = "1apePfXM1UOSqw0o9IiFAovVz9M5S1Dg+4TrDwfMewQ6p/rmMueb7tWZjQ1rx4Loy1ArBggoqGpfqqdI4rondg==";
          };
        };
        strip-ansi = {
          name = "strip-ansi";
          packageName = "strip-ansi";
          version = "5.2.0";
          tarball = {
            url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-5.2.0.tgz";
            sha512 = "DuRs1gKbBqsMKIZlrffwlug8MHkcnpjs5VPmL1PAh+mA30U0DTotfDZ0d2UUsXpPmPmMMJ6W773MaA3J+lbiWA==";
          };
        };
      };
    };
    string_decoder = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      tarball = {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    strip-ansi = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "4.0.0";
      tarball = {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-4.0.0.tgz";
        sha1 = "qEeQIusaw2iocTibY1JixQXuNo8=";
      };
    };
    strip-eof = {
      name = "strip-eof";
      packageName = "strip-eof";
      version = "1.0.0";
      tarball = {
        url = "https://registry.npmjs.org/strip-eof/-/strip-eof-1.0.0.tgz";
        sha1 = "u0P/VZim6wXYm1n80SnJgzE2Br8=";
      };
    };
    strip-json-comments = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "2.0.1";
      tarball = {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-2.0.1.tgz";
        sha1 = "PFMZQukIwml8DsNEhYwobHygpgo=";
      };
    };
    tar = {
      name = "tar";
      packageName = "tar";
      version = "4.4.8";
      tarball = {
        url = "https://registry.npmjs.org/tar/-/tar-4.4.8.tgz";
        sha512 = "LzHF64s5chPQQS0IYBn9IN5h3i98c12bo4NCO7e0sGM2llXQ3p2FGC5sdENN4cTW48O915Sh+x+EXx7XW96xYQ==";
      };
    };
    util-deprecate = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      tarball = {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "RQ1Nyfpw3nMnYvvS1KKJgUGaDM8=";
      };
    };
    which = {
      name = "which";
      packageName = "which";
      version = "1.3.1";
      bin = {
        which = "./bin/which";
      };
      tarball = {
        url = "https://registry.npmjs.org/which/-/which-1.3.1.tgz";
        sha512 = "HxJdYWq1MTIQbJ3nw0cqssHoTNU267KlrDuGZ1WYlxDStUtKUhOaJmh112/TZmHxxUfuJqPXSOm7tDyas0OSIQ==";
      };
    };
    which-module = {
      name = "which-module";
      packageName = "which-module";
      version = "2.0.0";
      tarball = {
        url = "https://registry.npmjs.org/which-module/-/which-module-2.0.0.tgz";
        sha1 = "2e8H3Od7mQK4o6j6SzHD4/fm6Ho=";
      };
    };
    wide-align = {
      name = "wide-align";
      packageName = "wide-align";
      version = "1.1.3";
      tarball = {
        url = "https://registry.npmjs.org/wide-align/-/wide-align-1.1.3.tgz";
        sha512 = "QGkOQc8XL6Bt5PwnsExKBPuMKBxnGxWWW3fU55Xt4feHozMUhdUMaBCk290qpm/wG5u/RSKzwdAC4i51YigihA==";
      };
      privateDependencies = {
        string-width = {
          name = "string-width";
          packageName = "string-width";
          version = "2.1.1";
          tarball = {
            url = "https://registry.npmjs.org/string-width/-/string-width-2.1.1.tgz";
            sha512 = "nOqH59deCq9SRHlxq1Aw85Jnt4w6KvLKqWVik6oA9ZklXLNIOlqg4F2yrT1MVaTjAqvVwdfeZ7w7aCvJD7ugkw==";
          };
        };
      };
    };
    wrap-ansi = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "2.1.0";
      tarball = {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-2.1.0.tgz";
        sha1 = "2Pw9KE3QV5T+hJc8rs3Rz4JP3YU=";
      };
      privateDependencies = {
        ansi-regex = {
          name = "ansi-regex";
          packageName = "ansi-regex";
          version = "2.1.1";
          tarball = {
            url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
            sha1 = "w7M6te42DYbg5ijwRorn7yfWVN8=";
          };
        };
        is-fullwidth-code-point = {
          name = "is-fullwidth-code-point";
          packageName = "is-fullwidth-code-point";
          version = "1.0.0";
          tarball = {
            url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
            sha1 = "754xOG8DGn8NZDr4L95QxFfvAMs=";
          };
        };
        string-width = {
          name = "string-width";
          packageName = "string-width";
          version = "1.0.2";
          tarball = {
            url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
            sha1 = "EYvfW4zcUaKn5w0hHgfisLmxB9M=";
          };
        };
        strip-ansi = {
          name = "strip-ansi";
          packageName = "strip-ansi";
          version = "3.0.1";
          tarball = {
            url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
            sha1 = "ajhfuIU9lS1f8F0Oiq+UJ43GPc8=";
          };
        };
      };
    };
    wrappy = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      tarball = {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "tSQ9jz7BqjXxNkYFvA0QNuMKtp8=";
      };
    };
    y18n = {
      name = "y18n";
      packageName = "y18n";
      version = "4.0.0";
      tarball = {
        url = "https://registry.npmjs.org/y18n/-/y18n-4.0.0.tgz";
        sha512 = "r9S/ZyXu/Xu9q1tYlpsLIsa3EeLXXk0VwlxqTcFRfg9EhMW+17kbt9G0NrgCmhGb5vT2hyhJZLfDGx+7+5Uj/w==";
      };
    };
    yallist = {
      name = "yallist";
      packageName = "yallist";
      version = "3.0.3";
      tarball = {
        url = "https://registry.npmjs.org/yallist/-/yallist-3.0.3.tgz";
        sha512 = "S+Zk8DEWE6oKpV+vI3qWkaK+jSbIK86pCwe2IF/xwIpQ8jEuxpw9NyaGjmp9+BoJv5FV2piqCDcoCtStppiq2A==";
      };
    };
    yargs = {
      name = "yargs";
      packageName = "yargs";
      version = "13.2.2";
      tarball = {
        url = "https://registry.npmjs.org/yargs/-/yargs-13.2.2.tgz";
        sha512 = "WyEoxgyTD3w5XRpAQNYUB9ycVH/PQrToaTXdYXRdOXvEy1l19br+VJsc0vcO8PTGg5ro/l/GY7F/JMEBmI0BxA==";
      };
    };
    yargs-parser = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "13.0.0";
      tarball = {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-13.0.0.tgz";
        sha512 = "w2LXjoL8oRdRQN+hOyppuXs+V/fVAYtpcrRxZuF7Kt/Oc+Jr2uAcVntaUTNT6w5ihoWfFDpNY8CPx1QskxZ/pw==";
      };
    };
  };
}
