#!/usr/bin/env bash

# Exit if any subcommand fails
set -e

# Switch to the project directory
cd "$(dirname "$0")/.."

node2nix --composition /dev/null --node-env /dev/null
sed -i "s/nodeEnv, //" node-packages.nix
sed -i -e ':a' -e 'N' -e '$!ba' -e "s/{\n  tarball = nodeEnv.buildNodeSourceDist args;\n  package = nodeEnv.buildNodePackage args;\n  shell = nodeEnv.buildNodeShell args;\n}/  args/" node-packages.nix
mv node-packages.nix node-package.nix
touch default.nix
